// How this deck was built, shown on the meta slide. Regenerated by scripts/build-stats.mjs
// from git and the QA artifacts, so every number here is measured, not estimated.
export const BUILD = {
  phases: [
    ['Tadqiqot', 'WebSearch', 'MCP, Agent Skills, 2026-yil freymvorklari tekshirildi'],
    ['Reja', 'plan', '45 daqiqalik sahna rejasi va MAKTAB freymvorki'],
    ['Kod', 'Write · Edit', 'dvigatel, 3D qatlam, slaydlar'],
    ['Tekshiruv', 'Playwright', 'har bir slayd skrinshot orqali koʻrib chiqildi'],
    ['Video', 'ffmpeg', 'agent animatsiyasi kadrma-kadr MP4 ga render qilindi'],
    ['Nashr', 'git · Artifact', 'repozitoriy va maxfiy havola'],
  ],
  stats: [
    ['29', 'slayd'],
    ['7 495', 'qator kod'],
    ['396', 'skrinshot tekshiruvi'],
    ['4 261', 'video kadr'],
  ],
};
