// How this deck was built, shown on the meta slide. Regenerated by scripts/build-stats.mjs
// from git and the QA artifacts, so every number here is measured, not estimated.
export const BUILD = {
  phases: [
    ['Tadqiqot', 'internetda qidiruv', 'mavzu boʻyicha eng yangi maʼlumotlar tekshirildi'],
    ['Reja', 'reja', '45 daqiqalik maʼruza rejasi va MAKTAB formulasi'],
    ['Kod', 'kod yozish', 'slaydlar, animatsiya va 3D'],
    ['Tekshiruv', 'skrinshot', 'har bir slaydni rasmga olib, oʻzi koʻrib chiqdi'],
    ['Video', 'video', 'agent animatsiyasi kadrma-kadr videoga aylantirildi'],
    ['Nashr', 'havola', 'tayyor fayl va havola'],
  ],
  stats: [
    ['20', 'slayd'],
    ['6 967', 'qator kod'],
    ['396', 'skrinshot tekshiruvi'],
    ['4 261', 'video kadr'],
  ],
};
