# Turn slide screenshots into small JPEG data URIs for the overview grid (Esc).
import sys, glob, base64, io, re, os
from PIL import Image
src, ids_file, out = sys.argv[1], sys.argv[2], sys.argv[3]
ids = open(ids_file).read().split()
lines = ['// Generated by scripts/make-thumbs.py from slide screenshots. Do not edit by hand.', 'export const THUMBS = {']
for i, sid in enumerate(ids):
    f = os.path.join(src, f'{i + 1:02d}.png')
    if not os.path.exists(f):
        continue
    im = Image.open(f).convert('RGB').resize((400, 225), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, 'JPEG', quality=72, optimize=True, progressive=True)
    lines.append(f"  '{sid}': 'data:image/jpeg;base64,{base64.b64encode(buf.getvalue()).decode()}',")
lines.append('};')
open(out, 'w').write('\n'.join(lines) + '\n')
print('thumbs', len(lines) - 3, os.path.getsize(out) // 1024, 'KB')
